/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7p2_rubenmaldonado;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ruben Dario Arias
 */
public class Princip extends javax.swing.JFrame {

    /**
     * Creates new form Princip
     */
    public Princip() {
        initComponents();
        this.setLocationRelativeTo(null);
        b = new AdministrarBarra(Bar);
    }

    ArrayList artistas = new ArrayList();
    ArrayList album = new ArrayList();
    ArrayList canciones = new ArrayList();
    ArrayList auxi = new ArrayList();
    public int auxiliar;
    public int auxiliar2;
    public int songs, artists, al;
    public int row;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        origen = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        Bar = new javax.swing.JProgressBar();
        jButton7 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        cancion = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        CrearArtistas = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombrear = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        generoar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        disqueraar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        aliasar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tipoar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        ListarArtistas = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        CrearAlbum = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        generoa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        digital = new javax.swing.JRadioButton();
        cd = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        aliasa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fechaa = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        grupo = new javax.swing.ButtonGroup();
        AgregarCancion = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nombrec = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        duracionc = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        compositorc = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        distric = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        si = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        productorc = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        artistac = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        VerAlbum = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableAlbum = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        ModificarAlbum = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        generoa1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        digital1 = new javax.swing.JRadioButton();
        cd1 = new javax.swing.JRadioButton();
        jLabel32 = new javax.swing.JLabel();
        aliasa1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        fechaa1 = new javax.swing.JFormattedTextField();
        jButton12 = new javax.swing.JButton();
        ModificarArtista = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        nombrear1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        generoar1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        disqueraar1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        aliasar1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        tipoar1 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        ListarCanciones = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableCanciones = new javax.swing.JTable();
        jButton18 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        origen.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 153, 51));
        jLabel26.setText("SPOTIFY");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Bar.setMaximum(400);
        jPanel2.add(Bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 280, -1));

        jButton7.setText("Reproducir");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Ingresel el nombre de la cancion a reproducir");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        jPanel2.add(cancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 230, -1));

        jButton16.setText("Pausar");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });
        jPanel2.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jButton17.setText("Continuar");
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton17MouseClicked(evt);
            }
        });
        jPanel2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab7p2_rubenmaldonado/fondoSpotify.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        origen.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        jMenu1.setText("Artistas");

        jMenuItem1.setText("Crear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Listar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        origen.setJMenuBar(jMenuBar1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel4.setText("Crear Artista");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel5.setText("Nombre");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        jPanel3.add(nombrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, -1));

        jLabel6.setText("Genero");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel3.add(generoar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, -1));

        jLabel7.setText("Disquera");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        jPanel3.add(disqueraar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, -1));

        jLabel8.setText("Alias");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));
        jPanel3.add(aliasar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 130, -1));

        jLabel9.setText("Tipo");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));
        jPanel3.add(tipoar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 130, -1));

        jButton2.setText("Completar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 180, -1));

        javax.swing.GroupLayout CrearArtistasLayout = new javax.swing.GroupLayout(CrearArtistas.getContentPane());
        CrearArtistas.getContentPane().setLayout(CrearArtistasLayout);
        CrearArtistasLayout.setHorizontalGroup(
            CrearArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        CrearArtistasLayout.setVerticalGroup(
            CrearArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("Artistas");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 100, 40));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Genero", "Disquera", "Alias", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 410, 90));

        jButton4.setText("Crear Album");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 100, -1));

        jButton6.setText("Ver Album");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        jButton9.setText("Eliminar Artista");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jButton14.setText("Modificar Artista");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        jPanel4.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        javax.swing.GroupLayout ListarArtistasLayout = new javax.swing.GroupLayout(ListarArtistas.getContentPane());
        ListarArtistas.getContentPane().setLayout(ListarArtistasLayout);
        ListarArtistasLayout.setHorizontalGroup(
            ListarArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ListarArtistasLayout.setVerticalGroup(
            ListarArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel11.setText("Crear Album");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel12.setText("Genero");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        jPanel5.add(generoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, -1));

        jLabel13.setText("Formato");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        grupo.add(digital);
        digital.setText("Digital");
        digital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitalActionPerformed(evt);
            }
        });
        jPanel5.add(digital, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        grupo.add(cd);
        cd.setText("Cd");
        jPanel5.add(cd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel14.setText("Alias Productor");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));
        jPanel5.add(aliasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 150, -1));

        jLabel15.setText("Fecha");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        try {
            fechaa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel5.add(fechaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 140, -1));

        jButton3.setText("Crear Album");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 150, -1));

        javax.swing.GroupLayout CrearAlbumLayout = new javax.swing.GroupLayout(CrearAlbum.getContentPane());
        CrearAlbum.getContentPane().setLayout(CrearAlbumLayout);
        CrearAlbumLayout.setHorizontalGroup(
            CrearAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );
        CrearAlbumLayout.setVerticalGroup(
            CrearAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel17.setText("Agregar Cancion");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel18.setText("Nombre");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 49, -1, -1));
        jPanel7.add(nombrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 70, 128, -1));

        jLabel19.setText("Duracion");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 120, -1, -1));

        duracionc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));
        jPanel7.add(duracionc, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 141, 128, -1));

        jLabel20.setText("Compositor");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 178, -1, -1));
        jPanel7.add(compositorc, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 199, 143, -1));

        jLabel21.setText("Distribuidor");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 230, -1, -1));
        jPanel7.add(distric, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 143, -1));

        jLabel22.setText("Es Exclusiva");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        buttonGroup1.add(si);
        si.setText("Si");
        jPanel7.add(si, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        buttonGroup1.add(no);
        no.setText("NO");
        jPanel7.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jLabel23.setText("Productor");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));
        jPanel7.add(productorc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 130, -1));

        jLabel24.setText("Artista Invitado");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel25.setText("(Opcional)");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));
        jPanel7.add(artistac, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 140, -1));

        jButton8.setText("Agregar Cancion");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jPanel7.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 150, -1));

        javax.swing.GroupLayout AgregarCancionLayout = new javax.swing.GroupLayout(AgregarCancion.getContentPane());
        AgregarCancion.getContentPane().setLayout(AgregarCancionLayout);
        AgregarCancionLayout.setHorizontalGroup(
            AgregarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );
        AgregarCancionLayout.setVerticalGroup(
            AgregarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel16.setText("Album del Artista");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        TableAlbum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Genero", "Formato", "Alias", "Album"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TableAlbum);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 490, 90));

        jButton5.setText("Agregar Cancion");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 120, 30));

        jButton10.setText("Eliminar Album");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jPanel6.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 110, 30));

        jButton11.setText("Modificar Album");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jPanel6.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 120, 30));

        jButton15.setText("Ver Canciones");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });
        jPanel6.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 110, 30));

        javax.swing.GroupLayout VerAlbumLayout = new javax.swing.GroupLayout(VerAlbum.getContentPane());
        VerAlbum.getContentPane().setLayout(VerAlbumLayout);
        VerAlbumLayout.setHorizontalGroup(
            VerAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );
        VerAlbumLayout.setVerticalGroup(
            VerAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel29.setText("Modificar Alumno");
        jPanel9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, -1));

        jLabel30.setText("Genero");
        jPanel9.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        jPanel9.add(generoa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, -1));

        jLabel31.setText("Formato");
        jPanel9.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        grupo.add(digital1);
        digital1.setText("Digital");
        digital1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digital1ActionPerformed(evt);
            }
        });
        jPanel9.add(digital1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        grupo.add(cd1);
        cd1.setText("Cd");
        jPanel9.add(cd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel32.setText("Alias Productor");
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));
        jPanel9.add(aliasa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 150, -1));

        jLabel33.setText("Fecha");
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        try {
            fechaa1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel9.add(fechaa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 140, -1));

        jButton12.setText("Modificar Alumno");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jPanel9.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 150, -1));

        javax.swing.GroupLayout ModificarAlbumLayout = new javax.swing.GroupLayout(ModificarAlbum.getContentPane());
        ModificarAlbum.getContentPane().setLayout(ModificarAlbumLayout);
        ModificarAlbumLayout.setHorizontalGroup(
            ModificarAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        ModificarAlbumLayout.setVerticalGroup(
            ModificarAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel28.setText("Modificar Artista");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel34.setText("Nombre");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        jPanel8.add(nombrear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, -1));

        jLabel35.setText("Genero");
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel8.add(generoar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, -1));

        jLabel36.setText("Disquera");
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        jPanel8.add(disqueraar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, -1));

        jLabel37.setText("Alias");
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));
        jPanel8.add(aliasar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 130, -1));

        jLabel38.setText("Tipo");
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));
        jPanel8.add(tipoar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 130, -1));

        jButton13.setText("Modificar");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jPanel8.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 180, -1));

        javax.swing.GroupLayout ModificarArtistaLayout = new javax.swing.GroupLayout(ModificarArtista.getContentPane());
        ModificarArtista.getContentPane().setLayout(ModificarArtistaLayout);
        ModificarArtistaLayout.setHorizontalGroup(
            ModificarArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        ModificarArtistaLayout.setVerticalGroup(
            ModificarArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel39.setText("Canciones");
        jPanel10.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        TableCanciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Duracion", "Compositor", "Distribuidor", "Exclusiva", "Productor", "Invitado", "Artista Propietario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TableCanciones);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 770, 90));

        jButton18.setText("Reproducir Cancion");
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton18MouseClicked(evt);
            }
        });
        jPanel10.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, -1, -1));

        javax.swing.GroupLayout ListarCancionesLayout = new javax.swing.GroupLayout(ListarCanciones.getContentPane());
        ListarCanciones.getContentPane().setLayout(ListarCancionesLayout);
        ListarCancionesLayout.setHorizontalGroup(
            ListarCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ListarCancionesLayout.setVerticalGroup(
            ListarCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("SPOTIFY");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("COMENZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab7p2_rubenmaldonado/spotify.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        origen.setModal(true);
        origen.pack();
        origen.setLocationRelativeTo(this);
        origen.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String n = nombrear.getText();
        String a = aliasar.getText();
        String d = disqueraar.getText();
        String g = generoar.getText();
        String t = tipoar.getText();
        nombrear.setText("");
        aliasar.setText("");
        disqueraar.setText("");
        generoar.setText("");
        tipoar.setText("");
        if (!"".equals(n) && !"".equals(a) && !"".equals(d) && !"".equals(g) && !"".equals(t)) {
            Artista aa = new Artista(n, g, d, a, t);
            artistas.add(aa);
            JOptionPane.showMessageDialog(origen, "Se ha registrado el artista correctamente");

            Object[] newrow = {n, g, d, a, t};
            DefaultTableModel modelo
                    = (DefaultTableModel) Table.getModel();
            modelo.addRow(newrow);
            Table.setModel(modelo);
        } else {
            JOptionPane.showMessageDialog(origen, "Debe completar los datos solicitados");
        }
        CrearArtistas.setVisible(false);


    }//GEN-LAST:event_jButton2MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CrearArtistas.setModal(true);
        CrearArtistas.pack();
        CrearArtistas.setLocationRelativeTo(origen);
        CrearArtistas.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ListarArtistas.setModal(true);
        ListarArtistas.pack();
        ListarArtistas.setLocationRelativeTo(origen);
        ListarArtistas.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        if (Table.getSelectedRow() >= 0) {
            DefaultTableModel modelo
                    = (DefaultTableModel) Table.getModel();
            Object name = modelo.getValueAt(Table.getSelectedRow(), 0);
            Object alias = modelo.getValueAt(Table.getSelectedRow(), 3);
            String n = name.toString();
            String a = alias.toString();
            for (int i = 0; i < artistas.size(); i++) {
                String aux = ((Artista) artistas.get(i)).getName();
                String aux2 = ((Artista) artistas.get(i)).getAlias();
                if (n.equals(aux) && a.equals(aux2)) {
                    auxiliar = i;
                    CrearAlbum.setModal(true);
                    CrearAlbum.pack();
                    CrearAlbum.setLocationRelativeTo(origen);
                    CrearAlbum.setVisible(true);
                }
            }
        } else {
            JOptionPane.showMessageDialog(ListarArtistas, "Debe seleccionar algun artista de la lista");
        }


    }//GEN-LAST:event_jButton4MouseClicked

    private void digitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_digitalActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        String g = generoa.getText();
        String a = aliasa.getText();
        String f = (String) fechaa.getValue();
        generoa.setText("");
        aliasa.setText("");
        fechaa.setValue(null);
        String formato = "";
        if (digital.isSelected()) {
            formato = "digital";
        } else if (cd.isSelected()) {
            formato = "cd";
        } else {
            formato = "digital/cd";
        }
        Album al = new Album(f, g, formato, a);
        album.add(al);
        ((Artista) artistas.get(auxiliar)).setAlbum(album);
        String s = ((Artista) artistas.get(auxiliar)).getName();
        JOptionPane.showMessageDialog(null, "El album ha sido creado exitosamente");
        CrearAlbum.setVisible(false);
        Archivos aaa = new Archivos(s, a);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        if (Table.getSelectedRow() >= 0) {
            DefaultTableModel modelo
                    = (DefaultTableModel) Table.getModel();
            Object name = modelo.getValueAt(Table.getSelectedRow(), 0);
            Object alias = modelo.getValueAt(Table.getSelectedRow(), 3);
            String n = name.toString();
            String a = alias.toString();
            try {
                for (int i = 0; i < artistas.size(); i++) {
                    String aux = ((Artista) artistas.get(i)).getName();
                    String aux2 = ((Artista) artistas.get(i)).getAlias();
                    if (n.equals(aux) && a.equals(aux2)) {
                        String fecha = ((Artista) artistas.get(i)).getName();
                        ArrayList<Album> temp = new ArrayList();
                        temp = ((Artista) artistas.get(i)).getAlbum();
                        auxi = temp;
                        auxiliar2 = i;

                        if (!temp.isEmpty()) {
                            String f = ((Album) temp.get(i)).getFecha();
                            String g = ((Album) temp.get(i)).getGenero();
                            String ff = ((Album) temp.get(i)).getFormato();
                            String alia = ((Album) temp.get(i)).getAliass();
                            Object[] newrow = {f, g, ff, alia, fecha};
                            DefaultTableModel modelo2
                                    = (DefaultTableModel) TableAlbum.getModel();
                            modelo2.addRow(newrow);
                            TableAlbum.setModel(modelo2);
                            Table.setModel(modelo);
                            VerAlbum.setModal(true);
                            VerAlbum.pack();
                            VerAlbum.setLocationRelativeTo(origen);
                            VerAlbum.setVisible(true);
                        } else {
                            JOptionPane.showMessageDialog(ListarArtistas, "Actualmente el artista no posee un album");
                        }

                    } else {
                        JOptionPane.showMessageDialog(ListarArtistas, "Debe seleccionar algun artista de la lista");
                    }
                }
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(VerAlbum, "Actualmente el artista no posee un album");
            }
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        String n = nombrec.getText();
        int duracion = ((Number) duracionc.getValue()).intValue();
        String c = compositorc.getText();
        String d = distric.getText();
        String p = productorc.getText();
        String exclusiva = "";
        String art = "";
        if (si.isSelected()) {
            exclusiva = "si";
        } else if (no.isSelected()) {
            exclusiva = "no";
        } else {
            exclusiva = "No Definido";
        }
        if ("".equals(artistac.getText())) {
            art = "No hubo";
        } else {
            art = artistac.getText();
        }
        nombrec.setText("");
        duracionc.setValue(null);
        compositorc.setText("");
        distric.setText("");
        productorc.setText("");
        artistac.setText("");
        Canciones can = new Canciones(n, duracion, c, d, exclusiva, p, art);
        canciones.add(can);
        ((Album) album.get(auxiliar)).getCanciones().add(can);
        AgregarCancion.setVisible(false);


    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        if (TableAlbum.getSelectedRow() >= 0) {
            row = TableAlbum.getSelectedRow();
            DefaultTableModel modelo
                    = (DefaultTableModel) TableAlbum.getModel();
            Object genero = modelo.getValueAt(TableAlbum.getSelectedRow(), 1);
            Object alias = modelo.getValueAt(TableAlbum.getSelectedRow(), 3);
            String n = genero.toString();
            String a = alias.toString();
            for (int i = 0; i < auxi.size(); i++) {
                String aux = ((Album) album.get(i)).getGenero();
                String aux2 = ((Album) album.get(i)).getAliass();
                if (n.equals(aux) && a.equals(aux2)) {
                    auxiliar = i;
                    AgregarCancion.setModal(true);
                    AgregarCancion.pack();
                    AgregarCancion.setLocationRelativeTo(origen);
                    AgregarCancion.setVisible(true);
                }
            }
        } else {
            JOptionPane.showMessageDialog(ListarArtistas, "Debe seleccionar algun album de la lista");
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        boolean flag = true;
        String nn = cancion.getText();
        for (int i = 0; i < canciones.size(); i++) {
            String c = ((Canciones) canciones.get(i)).getNombree();
            if (c.equals(nn)) {
                AdministrarBarra a = new AdministrarBarra(nn);
                b.start();
                b.setAvanzar(true);
                flag = false;
            }
        }
        if (flag == true) {
            JOptionPane.showMessageDialog(origen, "No se encontro la cancion que estaba buscando");
        }
        cancion.setText("");

    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        if (Table.getSelectedRow() >= 0) {
            row = Table.getSelectedRow();
            DefaultTableModel modelo
                    = (DefaultTableModel) Table.getModel();
            Object name = modelo.getValueAt(Table.getSelectedRow(), 0);
            Object alias = modelo.getValueAt(Table.getSelectedRow(), 3);
            String n = name.toString();
            String a = alias.toString();
            modelo.removeRow(Table.getSelectedRow());
            Table.setModel(modelo);
            for (int i = 0; i < artistas.size(); i++) {
                String aux = ((Artista) artistas.get(i)).getName();
                String aux2 = ((Artista) artistas.get(i)).getAlias();
                if (n.equals(aux) && a.equals(aux2)) {
                    artistas.remove(i);
                }

            }

        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        if (TableAlbum.getSelectedRow() >= 0) {
            DefaultTableModel modelo
                    = (DefaultTableModel) TableAlbum.getModel();
            Object genero = modelo.getValueAt(TableAlbum.getSelectedRow(), 1);
            Object alias = modelo.getValueAt(TableAlbum.getSelectedRow(), 3);
            String n = genero.toString();
            String a = alias.toString();
            modelo.removeRow(TableAlbum.getSelectedRow());
            TableAlbum.setModel(modelo);
            for (int i = 0; i < auxi.size(); i++) {
                String aux = ((Album) album.get(i)).getGenero();
                String aux2 = ((Album) album.get(i)).getAliass();
                if (n.equals(aux) && a.equals(aux2)) {
                    album.remove(i);
                }
            }
        } else {
            JOptionPane.showMessageDialog(ListarArtistas, "Debe seleccionar algun album de la lista");
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void digital1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digital1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_digital1ActionPerformed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked

        String g = generoa1.getText();
        String a = aliasa1.getText();
        String f = (String) fechaa1.getValue();
        String formato = "";
        if (digital1.isSelected()) {
            formato = "digital";
        } else if (cd1.isSelected()) {
            formato = "cd";
        } else {
            formato = "digital/cd";
        }
        Album all = new Album(f, g, formato, a);
        album.set(auxiliar, all);
        ((Artista) artistas.get(auxiliar)).setAlbum(album);
        JOptionPane.showMessageDialog(null, "El album ha sido Modificado exitosamente");
        DefaultTableModel modelo
                = (DefaultTableModel) TableAlbum.getModel();
        modelo.removeRow(row);
        Object[] newrow = {f, g, formato, a};
        modelo.addRow(newrow);
        TableAlbum.setModel(modelo);
        ModificarAlbum.setVisible(false);
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        if (TableAlbum.getSelectedRow() >= 0) {
            row = TableAlbum.getSelectedRow();
            DefaultTableModel modelo
                    = (DefaultTableModel) TableAlbum.getModel();
            Object genero = modelo.getValueAt(TableAlbum.getSelectedRow(), 1);
            Object alias = modelo.getValueAt(TableAlbum.getSelectedRow(), 3);
            String n = genero.toString();
            String a = alias.toString();
            for (int i = 0; i < auxi.size(); i++) {
                String aux = ((Album) album.get(i)).getGenero();
                String aux2 = ((Album) album.get(i)).getAliass();
                if (n.equals(aux) && a.equals(aux2)) {
                    String f = ((Album) album.get(i)).getFecha();
                    String ff = ((Album) album.get(i)).getFormato();
                    generoa1.setText(n);
                    fechaa1.setValue(f);
                    aliasa1.setText(a);
                    auxiliar = i;
                    ModificarAlbum.setModal(true);
                    ModificarAlbum.pack();
                    ModificarAlbum.setLocationRelativeTo(origen);
                    ModificarAlbum.setVisible(true);
                }
            }
        } else {
            JOptionPane.showMessageDialog(ListarArtistas, "Debe seleccionar algun album de la lista");
        }
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        String n = nombrear1.getText();
        String a = aliasar1.getText();
        String d = disqueraar1.getText();
        String g = generoar1.getText();
        String t = tipoar1.getText();
        if (!"".equals(n) && !"".equals(a) && !"".equals(d) && !"".equals(g) && !"".equals(t)) {
            Artista aa = new Artista(n, g, d, a, t);
            artistas.set(auxiliar, aa);
            JOptionPane.showMessageDialog(origen, "Se ha Modificado el artista correctamente");

            Object[] newrow = {n, g, d, a, t};
            DefaultTableModel modelo
                    = (DefaultTableModel) Table.getModel();
            modelo.removeRow(row);
            modelo.addRow(newrow);
            Table.setModel(modelo);
        } else {
            JOptionPane.showMessageDialog(origen, "Debe completar los datos solicitados");
        }
        ModificarArtista.setVisible(false);
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        if (Table.getSelectedRow() >= 0) {
            DefaultTableModel modelo
                    = (DefaultTableModel) Table.getModel();
            row = Table.getSelectedRow();
            Object name = modelo.getValueAt(Table.getSelectedRow(), 0);
            Object alias = modelo.getValueAt(Table.getSelectedRow(), 3);
            String n = name.toString();
            String a = alias.toString();
            for (int i = 0; i < artistas.size(); i++) {
                String aux = ((Artista) artistas.get(i)).getName();
                String aux2 = ((Artista) artistas.get(i)).getAlias();
                if (n.equals(aux) && a.equals(aux2)) {
                    String g = ((Artista) artistas.get(i)).getGender();
                    String d = ((Artista) artistas.get(i)).getDisquera();
                    String t = ((Artista) artistas.get(i)).getTipo();
                    nombrear1.setText(n);
                    aliasar1.setText(a);
                    disqueraar1.setText(d);
                    generoar1.setText(g);
                    tipoar1.setText(t);
                    auxiliar = i;
                    ModificarArtista.setModal(true);
                    ModificarArtista.pack();
                    ModificarArtista.setLocationRelativeTo(origen);
                    ModificarArtista.setVisible(true);
                }
            }
        } else {
            JOptionPane.showMessageDialog(ListarArtistas, "Debe seleccionar algun artista de la lista");
        }
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        if (TableAlbum.getSelectedRow() >= 0) {
            row = TableAlbum.getSelectedRow();
            DefaultTableModel modelo
                    = (DefaultTableModel) TableAlbum.getModel();
            Object genero = modelo.getValueAt(TableAlbum.getSelectedRow(), 1);
            Object alias = modelo.getValueAt(TableAlbum.getSelectedRow(), 3);
            String n = genero.toString();
            String a = alias.toString();
            for (int i = 0; i < auxi.size(); i++) {
                String aux = ((Album) album.get(i)).getGenero();
                String aux2 = ((Album) album.get(i)).getAliass();
                if (n.equals(aux) && a.equals(aux2)) {
                    ArrayList temp = new ArrayList();
                    temp = ((Album) album.get(row)).getCanciones();
                    if (!temp.isEmpty()) {
                        DefaultTableModel modelo2
                                = (DefaultTableModel) TableCanciones.getModel();
                        for (int ii = 0; ii < temp.size(); ii++) {
                            String nombre = ((Canciones) temp.get(ii)).getNombree();
                            int duracion = ((Canciones) temp.get(ii)).getDuracion();
                            String dist = ((Canciones) temp.get(ii)).getDistri();
                            String compo = ((Canciones) temp.get(ii)).getCompositor();
                            String exclu = ((Canciones) temp.get(ii)).getExlusiva();
                            String prod = ((Canciones) temp.get(ii)).getNombreProductor();
                            String invi = ((Canciones) temp.get(ii)).getInvitado();
                            String original = ((Artista) artistas.get(row)).getName();
                            Object[] newrow = {nombre, duracion, dist, compo, exclu, prod, invi, original};
                            modelo2.addRow(newrow);
                        }
                        TableCanciones.setModel(modelo2);
                        ListarCanciones.setModal(true);
                        ListarCanciones.pack();
                        ListarCanciones.setLocationRelativeTo(origen);
                        ListarCanciones.setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(VerAlbum, "No tiene canciones disponibles");
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(ListarArtistas, "Debe seleccionar algun album de la lista");
        }
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        b.setAvanzar(false);
    }//GEN-LAST:event_jButton16MouseClicked

    private void jButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseClicked
        if (TableCanciones.getSelectedRow() >= 0) {
            DefaultTableModel modelo
                    = (DefaultTableModel) TableCanciones.getModel();
            row = TableCanciones.getSelectedRow();
            Object name = modelo.getValueAt(TableCanciones.getSelectedRow(), 0);
            String n = name.toString();
            for (int i = 0; i < canciones.size(); i++) {
                String aux = ((Canciones) canciones.get(i)).getNombree();
                if (n.equals(aux)) {
                    auxiliar = i;
                    ListarCanciones.setVisible(false);
                    VerAlbum.setVisible(false);
                    ListarArtistas.setVisible(false);
                    AdministrarBarra bb = new AdministrarBarra(n);
                    b.start();
                    b.setAvanzar(true);
                }else{
                    JOptionPane.showMessageDialog(ListarCanciones, "No se puede reproducir");
                }
            }
        } else {
            JOptionPane.showMessageDialog(ListarCanciones, "Debe seleccionar alguna cancion de la lista");
        }
    }//GEN-LAST:event_jButton18MouseClicked

    private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
       b.setAvanzar(true);
    }//GEN-LAST:event_jButton17MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Princip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Princip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Princip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Princip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Princip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AgregarCancion;
    private javax.swing.JProgressBar Bar;
    private javax.swing.JDialog CrearAlbum;
    private javax.swing.JDialog CrearArtistas;
    private javax.swing.JDialog ListarArtistas;
    private javax.swing.JDialog ListarCanciones;
    private javax.swing.JDialog ModificarAlbum;
    private javax.swing.JDialog ModificarArtista;
    private javax.swing.JTable Table;
    private javax.swing.JTable TableAlbum;
    private javax.swing.JTable TableCanciones;
    private javax.swing.JDialog VerAlbum;
    private javax.swing.JTextField aliasa;
    private javax.swing.JTextField aliasa1;
    private javax.swing.JTextField aliasar;
    private javax.swing.JTextField aliasar1;
    private javax.swing.JTextField artistac;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cancion;
    private javax.swing.JRadioButton cd;
    private javax.swing.JRadioButton cd1;
    private javax.swing.JTextField compositorc;
    private javax.swing.JRadioButton digital;
    private javax.swing.JRadioButton digital1;
    private javax.swing.JTextField disqueraar;
    private javax.swing.JTextField disqueraar1;
    private javax.swing.JTextField distric;
    private javax.swing.JFormattedTextField duracionc;
    private javax.swing.JFormattedTextField fechaa;
    private javax.swing.JFormattedTextField fechaa1;
    private javax.swing.JTextField generoa;
    private javax.swing.JTextField generoa1;
    private javax.swing.JTextField generoar;
    private javax.swing.JTextField generoar1;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton no;
    private javax.swing.JTextField nombrear;
    private javax.swing.JTextField nombrear1;
    private javax.swing.JTextField nombrec;
    private javax.swing.JDialog origen;
    private javax.swing.JTextField productorc;
    private javax.swing.JRadioButton si;
    private javax.swing.JTextField tipoar;
    private javax.swing.JTextField tipoar1;
    // End of variables declaration//GEN-END:variables
AdministrarBarra b;
}
